services:
  postgres:
    image: postgres:15
    container_name: userflow-db
    environment:
      POSTGRES_DB: userflow
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d userflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: userflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  file-storage:
    build:
      context: ./file-storing-service
      dockerfile: Dockerfile
    container_name: storage-service
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userflow
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345

  file-analysis-service:
    build:
      context: ./file-analisys-service
      dockerfile: Dockerfile
    container_name: file-analysis-service
    ports:
      - 9091:9091
    depends_on:
       file-storage:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userflow
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345

  gateway-api:
    build:
      context: ./gateway-api
      dockerfile: Dockerfile
    container_name: gateway-api
    ports:
      - 8080:8080
    depends_on:
      - file-storage
      - file-analysis-service



volumes:
  postgres_data:
  minio_data: